
const db={appointments:JSON.parse(localStorage.getItem('mb_appts')||'[]'),clients:JSON.parse(localStorage.getItem('mb_clients')||'[]'),services:JSON.parse(localStorage.getItem('mb_services')||'[]'),barbers:JSON.parse(localStorage.getItem('mb_barbers')||'[]'),sales:JSON.parse(localStorage.getItem('mb_sales')||'[]'),cashClosings:JSON.parse(localStorage.getItem('mb_cash_closings')||'[]'),business:JSON.parse(localStorage.getItem('mb_business')||'{"name":"Mi Barbería","phone":"","address":""}')};
function el(id){return document.getElementById(id)}
function save(){localStorage.setItem('mb_appts',JSON.stringify(db.appointments));localStorage.setItem('mb_clients',JSON.stringify(db.clients));localStorage.setItem('mb_services',JSON.stringify(db.services));localStorage.setItem('mb_barbers',JSON.stringify(db.barbers));localStorage.setItem('mb_sales',JSON.stringify(db.sales));localStorage.setItem('mb_cash_closings',JSON.stringify(db.cashClosings));localStorage.setItem('mb_business',JSON.stringify(db.business));render()}
function show(id,b){document.querySelectorAll('.module').forEach(x=>x.classList.remove('active'));const s=el(id);if(s)s.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active')}
function goto(id){const b=[...document.querySelectorAll('nav button')].find(x=>(x.getAttribute('onclick')||'').includes("'"+id+"'"));show(id,b)}
function localDay(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function saleDay(x){return localDay(new Date(x.date))}
function money(n){return '$'+Number(n||0).toLocaleString('es-CO')}
function addAppointment(){const n=el('aName').value.trim();if(!n||!el('aDate').value||!el('aTime').value)return alert('Completa cliente, fecha y hora.');db.appointments.push({id:Date.now(),name:n,phone:el('aPhone').value,date:el('aDate').value,time:el('aTime').value,service:el('aService').value,status:'Programada'});el('aName').value='';el('aPhone').value='';save()}
function addClient(){const n=el('cName').value.trim();if(!n)return alert('Escribe el nombre del cliente.');db.clients.push({id:Date.now(),name:n,phone:el('cPhone').value});el('cName').value='';el('cPhone').value='';save()}
function addService(){const n=el('sName').value.trim(),p=Number(el('sPrice').value);if(!n||!p)return alert('Completa servicio y precio.');db.services.push({id:Date.now(),name:n,price:p});el('sName').value='';el('sPrice').value='';save()}
function addBarber(){const n=el('bName').value.trim(),p=Number(el('bCommission').value);if(!n)return alert('Escribe el nombre del profesional.');if(p<0||p>100)return alert('La comisión debe estar entre 0 y 100%.');db.barbers.push({id:Date.now(),name:n,commission:p||0});el('bName').value='';el('bCommission').value='';save()}
function addSale(){const amount=Number(el('vAmount').value),barber=el('vBarber').value;if(!amount)return alert('Ingresa el valor cobrado.');if(!barber)return alert('Selecciona el profesional.');db.sales.push({id:Date.now(),client:el('vClient').value.trim()||'Cliente general',service:el('vService').value||'Servicio',barber,method:el('vMethod').value,amount,date:new Date().toISOString()});el('vClient').value='';el('vAmount').value='';save()}
function closeCash(){const today=localDay(),ts=db.sales.filter(x=>saleDay(x)===today),total=ts.reduce((a,x)=>a+Number(x.amount),0);if(!ts.length)return alert('Todavía no hay ventas para cerrar.');const existing=db.cashClosings.find(x=>x.date===today);if(existing)return alert('La caja de hoy ya fue cerrada.');if(!confirm('¿Cerrar la caja de hoy por '+money(total)+'?'))return;db.cashClosings.push({id:Date.now(),date:today,total,closedAt:new Date().toISOString()});save();alert('Caja cerrada correctamente.')}
function saveBusiness(){const name=el('businessName').value.trim();if(!name)return alert('Escribe el nombre del negocio.');db.business={name:name,phone:el('businessPhone').value.trim(),address:el('businessAddress').value.trim()};save();alert('Configuración guardada correctamente.')}
function reportSales(){const p=el('reportPeriod')?el('reportPeriod').value:'today',now=new Date(),today=localDay(now);return db.sales.filter(x=>{const d=new Date(x.date);if(p==='today')return saleDay(x)===today;if(p==='week')return d>=new Date(now.getFullYear(),now.getMonth(),now.getDate()-6);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()})}
function renderReports(){if(!el('rSales'))return;const rs=reportSales(),total=rs.reduce((a,x)=>a+Number(x.amount),0);el('rSales').textContent=money(total);el('rServices').textContent=rs.length;el('rTicket').textContent=money(rs.length?Math.round(total/rs.length):0);el('rClients').textContent=new Set(rs.map(x=>x.client).filter(x=>x&&x!=='Cliente general')).size;const methods=['Efectivo','Transferencia','Tarjeta','Otro'];el('rPayments').innerHTML=methods.map(m=>'<div class="row"><span>'+m+'</span><b>'+money(rs.filter(x=>x.method===m).reduce((a,x)=>a+Number(x.amount),0))+'</b></div>').join('');el('rTeam').innerHTML=db.barbers.map(b=>{const prod=rs.filter(x=>x.barber===b.name).reduce((a,x)=>a+Number(x.amount),0),com=prod*Number(b.commission)/100;return '<div class="row"><span><b>'+b.name+'</b><br><small>Producción '+money(prod)+'</small></span><span>Comisión '+money(com)+'</span></div>'}).join('')||'<div class="empty">Sin profesionales registrados.</div>'}
function render(){el('businessName').value=db.business.name||'';el('businessPhone').value=db.business.phone||'';el('businessAddress').value=db.business.address||'';el('topBusinessName').textContent=db.business.name||'Mi Barbería';el('agendaList').innerHTML=db.appointments.map(x=>'<div class="row"><span><b>'+x.time+' · '+x.name+'</b><br><small>'+x.date+' · '+x.service+'</small></span><span>'+(x.status||'Programada')+'</span></div>').join('')||'<div class="empty">Sin citas.</div>';el('clientList').innerHTML=db.clients.map(x=>'<div class="row"><b>'+x.name+'</b><small>'+x.phone+'</small></div>').join('')||'<div class="empty">Sin clientes.</div>';el('servicesList').innerHTML=db.services.map(x=>'<div class="row"><b>'+x.name+'</b><span>'+money(x.price)+'</span></div>').join('')||'<div class="empty">Sin servicios.</div>';el('barberList').innerHTML=db.barbers.map(x=>{const prod=db.sales.filter(s=>s.barber===x.name).reduce((a,s)=>a+Number(s.amount),0),com=prod*Number(x.commission)/100;return '<div class="row"><span><b>'+x.name+'</b><br><small>Producción '+money(prod)+' · Comisión '+x.commission+'%</small></span><b>'+money(com)+'</b></div>'}).join('')||'<div class="empty">Aún no hay profesionales registrados.</div>';el('vService').innerHTML=db.services.map(x=>'<option value="'+x.name+'">'+x.name+'</option>').join('')||'<option>Servicio general</option>';el('vBarber').innerHTML='<option value="">Selecciona profesional</option>'+db.barbers.map(x=>'<option value="'+x.name+'">'+x.name+'</option>').join('');el('salesList').innerHTML=db.sales.slice().reverse().map(x=>'<div class="row"><span><b>'+x.service+' · '+x.client+'</b><br><small>'+x.barber+' · '+x.method+'</small></span><b>'+money(x.amount)+'</b></div>').join('')||'<div class="empty">Aún no hay ventas registradas.</div>';const today=localDay(),ta=db.appointments.filter(x=>x.date===today),ts=db.sales.filter(x=>saleDay(x)===today),total=ts.reduce((a,x)=>a+Number(x.amount),0);el('apptCount').textContent=ta.length;el('clientsCount').textContent=new Set(ts.map(x=>x.client).filter(x=>x&&x!=='Cliente general')).size;el('serviceCount').textContent=ts.length;el('sales').textContent=money(total);const by=m=>ts.filter(x=>x.method===m).reduce((a,x)=>a+Number(x.amount),0);el('cashTotal').textContent=money(by('Efectivo'));el('transferTotal').textContent=money(by('Transferencia'));el('cardTotal').textContent=money(by('Tarjeta'));el('otherTotal').textContent=money(by('Otro'));el('cashGrandTotal').textContent=money(total);const closing=db.cashClosings.find(x=>x.date===today);el('cashCloseInfo').textContent=closing?'✓ Caja cerrada · '+money(closing.total):'Caja abierta';el('todayList').className=ta.length?'':'empty';el('todayList').innerHTML=ta.map(x=>'<div class="appt"><b>'+x.time+'</b><span>'+x.name+'<br><small>'+x.service+'</small></span><span class="status">'+(x.status||'Programada')+'</span></div>').join('')||'Todavía no hay citas registradas.'};renderReports()
render();
